unAudicle issue tracking

* BUGS
** DONE When creating new revision, old revision not preserved.
   The fix works like this:
   Before you undo the parent buffer, disconnect textChanged() signal.
   Then after you undo, you can reconnect it.
** DONE Bugs with gridlayout when getting rid of shreds.
   This is not a bug anymore, we don't use the gridLayout-based anymore.
** DONE We lose focus after creating the new buffers.
   Calling setActiveSubWindow() after creating window does the trick.
** DONE When we don't have focus, the shredding function doesn't work.
   We use the subWindowList with stacking order to get top window.
** TODO After creating a few revisions and shredding them,
   text in buffer does not match the text that successfully shredded.
** DONE After creating a new revision, selection in tree widget does not follow.
   created a signal in codeArea, selectedRevision, and connected it to shredTree

* Feature Ideas
** Support Supercollider.
** Make a better revision tree visualization.
*** Try implementing the ordered tree layout algorithm in trees.pdf.
** Automatically delete empty sessions.
** Save information for replaying a session.
** Make a shred action "fadeOut".
** Support File, New Buffer.
** Extend and use the macro system (maybe with arg macros)
   to support global variable declarations in chuck.
** Try to make a signals and slots way to interact with tree viz.

* Stupid Feature Ideas
** Make a configurable splash screen.

